
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: subscription_service_app
    ports:
      - "8080:8080"
    environment:
      DATABASE_CONNECTION_STRING: postgresql://postgres:password@db:5432/subscriptions_db?sslmode=disable
    depends_on:
      db:
          condition: service_healthy

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: subscriptions_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d subscriptions_db'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  db: