// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package client

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// AggregationResult defines model for AggregationResult.
type AggregationResult struct {
	TotalCost int `json:"total_cost"`
}

// CreateSubscriptionRequest defines model for CreateSubscriptionRequest.
type CreateSubscriptionRequest struct {
	EndDate     *string            `json:"end_date"`
	Price       int                `json:"price"`
	ServiceName string             `json:"service_name"`
	StartDate   string             `json:"start_date"`
	UserId      openapi_types.UUID `json:"user_id"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Errors *string `json:"errors"`
}

// Subscription defines model for Subscription.
type Subscription struct {
	CreatedAt   *time.Time          `json:"created_at,omitempty"`
	EndDate     *string             `json:"end_date"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Price       int                 `json:"price"`
	ServiceName string              `json:"service_name"`
	StartDate   string              `json:"start_date"`
	UpdatedAt   *time.Time          `json:"updated_at,omitempty"`
	UserId      openapi_types.UUID  `json:"user_id"`
}

// UpdateSubscriptionRequest defines model for UpdateSubscriptionRequest.
type UpdateSubscriptionRequest struct {
	EndDate     *string `json:"end_date"`
	Price       int     `json:"price"`
	ServiceName string  `json:"service_name"`
	StartDate   string  `json:"start_date"`
}

// GetSubscriptionsParams defines parameters for GetSubscriptions.
type GetSubscriptionsParams struct {
	UserId      *openapi_types.UUID `form:"user_id,omitempty" json:"user_id,omitempty"`
	ServiceName *string             `form:"service_name,omitempty" json:"service_name,omitempty"`
	Price       *int                `form:"price,omitempty" json:"price,omitempty"`
	StartDate   *string             `form:"start_date,omitempty" json:"start_date,omitempty"`
	EndDate     *string             `form:"end_date,omitempty" json:"end_date,omitempty"`
	Limit       *int                `form:"limit,omitempty" json:"limit,omitempty"`
	Offset      *int                `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetSubscriptionsSumParams defines parameters for GetSubscriptionsSum.
type GetSubscriptionsSumParams struct {
	// StartDate Начало периода (MM-YYYY)
	StartDate string `form:"start_date" json:"start_date"`

	// EndDate Конец периода (MM-YYYY)
	EndDate     string              `form:"end_date" json:"end_date"`
	UserId      *openapi_types.UUID `form:"user_id,omitempty" json:"user_id,omitempty"`
	ServiceName *string             `form:"service_name,omitempty" json:"service_name,omitempty"`
}

// PostSubscriptionsJSONRequestBody defines body for PostSubscriptions for application/json ContentType.
type PostSubscriptionsJSONRequestBody = CreateSubscriptionRequest

// PutSubscriptionsIdJSONRequestBody defines body for PutSubscriptionsId for application/json ContentType.
type PutSubscriptionsIdJSONRequestBody = UpdateSubscriptionRequest
