openapi: 3.0.3
info:
  title: Subscription Service API
  description: REST-сервис для агрегации данных об онлайн-подписках пользователей
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /subscriptions:
    post:
      summary: Создать подписку
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSubscriptionRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      summary: Список подписок
      parameters:
        - name: user_id
          in: query
          required: false
          schema:
            type: string
            format: uuid
            pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
            example: 60601fee-2bf1-4721-ae6f-7636e79a0cba
        - name: service_name
          in: query
          required: false
          schema:
            type: string
            pattern: '^[a-zA-Z0-9а-яА-ЯёЁ\\s\\-\\+]+$'
            minLength: 1
            maxLength: 255
            example: Yandex Plus
        - name: price
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
            maximum: 1000000
            example: 500
        - name: start_date
          in: query
          required: false
          schema:
            type: string
            pattern: '^(0[1-9]|1[0-2])-20\d{2}$'
            example: "07-2025"
        - name: end_date
          in: query
          required: false
          schema:
            type: string
            pattern: '^(0[1-9]|1[0-2])-20\d{2}$'
            example: "12-2025"
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 1000
            example: 10
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
            maximum: 10000
            example: 0
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subscription'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /subscriptions/{id}:
    get:
      summary: Получить подписку по ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
            pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      summary: Обновить подписку
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
            pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSubscriptionRequest'
      responses:
        '204':
          description: Updated
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Уд.лить подписку
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
            pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /subscriptions/sum:
    get:
      summary: Агрегация стоимости подписок
      parameters:
        - name: start_date
          in: query
          required: true
          schema:
            type: string
            pattern: '^(0[1-9]|1[0-2])-20\d{2}$'
        - name: end_date
          in: query
          required: true
          schema:
            type: string
            pattern: '^(0[1-9]|1[0-2])-20\d{2}$'
        - name: user_id
          in: query
          required: false
          schema:
            type: string
            format: uuid
            pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
        - name: service_name
          in: query
          required: false
          schema:
            type: string
            pattern: '^[a-zA-Z0-9а-яА-ЯёЁ\\s\\-\\+]+$'
            minLength: 1
            maxLength: 255
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AggregationResult'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Subscription:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        service_name:
          type: string
          example: Yandex Plus
        price:
          type: integer
          minimum: 0
          example: 400
        user_id:
          type: string
          format: uuid
          example: 60601fee-2bf1-4721-ae6f-7636e79a0cba
        start_date:
          type: string
          pattern: '^(0[1-9]|1[0-2])-20\d{2}$'
          example: "07-2025"
        end_date:
          type: string
          nullable: true
          pattern: '^(0[1-9]|1[0-2])-20\d{2}$'
          example: "12-2025"
        created_at:
          type: string
          format: date-time
          readOnly: true
          example: "2025-07-15T10:30:00Z"
        updated_at:
          type: string
          format: date-time
          readOnly: true
          example: "2025-07-15T10:30:00Z"
      required:
        - id
        - service_name
        - price
        - user_id
        - start_date
        - created_at
        - updated_at

    CreateSubscriptionRequest:
      type: object
      properties:
        service_name:
          type: string
          example: Yandex Plus
        price:
          type: integer
          minimum: 0
          example: 400
        user_id:
          type: string
          format: uuid
          example: 60601fee-2bf1-4721-ae6f-7636e79a0cba
        start_date:
          type: string
          pattern: '^(0[1-9]|1[0-2])-20\d{2}$'
          example: "07-2025"
        end_date:
          type: string
          nullable: true
          pattern: '^(0[1-9]|1[0-2])-20\d{2}$'
          example: "12-2025"
      required:
        - service_name
        - price
        - user_id
        - start_date

    UpdateSubscriptionRequest:
      type: object
      properties:
        service_name:
          type: string
          example: Updated Service
        price:
          type: integer
          minimum: 0
          example: 500
        start_date:
          type: string
          pattern: '^(0[1-9]|1[0-2])-20\d{2}$'
          example: "08-2025"
        end_date:
          type: string
          nullable: true
          pattern: '^(0[1-9]|1[0-2])-20\d{2}$'
          example: null
      required:
        - service_name
        - price
        - start_date

    AggregationResult:
      type: object
      properties:
        total_cost:
          type: integer
          minimum: 0
          example: 1200
      required:
        - total_cost

    ErrorResponse:
      type: object
      properties:
        errors:
          type: string
          nullable: true
          example: "Validation failed: start_date has invalid format"
      required:
        - errors